### ISSUE TITLE
Plugin for the `cs:warm-node` command?

### ISSUE THREAD

**Issue by jtomaszewski** [mageops/ansible-infrastructure#100]
I see that in one of your scripts you're calling a `magento cs:warm-node` command, which unfortunately is not present in my magento2 installation.

Is that something that you implemented with a magento2 plugin? Any chance to see it open-sourced?

I'm curious what exactly is covered by that script, because now I'm wondering if I have to e.g. clear Varnish cache somehow manually during the app deploy [if it's done by that script], or anything else. 🤔  😛

**Comment by krisdante** [comment]
I am shocked we missed that out. 
Now it is uploaded: https://github.com/mageops/node-warmer-extension
