### ISSUE TITLE
Eliminate dependency on exact_count param when starting EC2

### ISSUE THREAD

**Issue by krisdante** [mageops/ansible-infrastructure#3]
# Background

In a few roles, we rely on the parameter
```
- name: Create builder instance
  ec2:
    ...
    exact_count: 1
```

This parameter makes us sure that there will be only one such machine.
# Problem

This however in some corner cases leads to a situation that another machine is spun in different Availability Zone (detail not important for now). 

# Need

We want to improve that at some point and to do that we want to get rid of the exact count parameter. Instead of that, there shall be ec2 facts collected before and based on tags it shall determine if the machine is up or not - and skip creation.

**Comment by pinkeen** [comment]
Fixed by #41
